"""FAD initialization followed by differentiable gradient matching.

The decoder supplies an image-space initialization. Refinement minimizes the
discrepancy between observed target gradients and gradients generated by the
candidate image. The classifier scope is a cheap sanity check; the full scope
uses every trainable target-model parameter and is substantially more
expensive because it requires second-order derivatives.
"""

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F
from torch.nn import CrossEntropyLoss
from torch.utils.data import DataLoader
from torchvision.utils import save_image

from attack_decoder_multidataset import (
    compute_id_loss,
    compute_psnr,
    compute_ssim,
    load_decoder,
    recover_feat_from_fc_grad,
    save_pair,
)
from experiment_utils import seed_everything, summarize_values
from train_decoder_multidataset import (
    DEVICE,
    build_dataset,
    build_transform,
    load_target_model,
    target_model_input,
)


def total_variation(x):
    return (
        (x[:, :, 1:, :] - x[:, :, :-1, :]).abs().mean()
        + (x[:, :, :, 1:] - x[:, :, :, :-1]).abs().mean()
    )


def normalized_gradient_loss(candidate, target):
    terms = []
    for current, reference in zip(candidate, target):
        reference = reference.detach()
        scale = reference.detach().norm().clamp_min(1e-8)
        terms.append(((current - reference) / scale).pow(2).mean())
    return torch.stack(terms).mean() if terms else torch.zeros((), device=DEVICE)


def image_pair_save(real, recon, output_dir, name):
    raw_dir = Path(output_dir) / "raw_pairs"
    raw_dir.mkdir(parents=True, exist_ok=True)
    save_image(torch.clamp((real.detach().cpu() + 1) / 2, 0, 1), raw_dir / f"{name}_real.png")
    save_image(torch.clamp((recon.detach().cpu() + 1) / 2, 0, 1), raw_dir / f"{name}_recon.png")


def select_parameters(model, scope):
    if scope == "classifier":
        names = {"fc_layer.weight", "fc_layer.bias"}
        selected = [(name, param) for name, param in model.named_parameters() if name in names]
    else:
        selected = [(name, param) for name, param in model.named_parameters() if param.requires_grad]
    if not selected:
        raise RuntimeError(f"No target parameters selected for gradient_scope={scope}")
    return selected


def gradients_for_image(model, image, label, parameters, dataset_name, create_graph):
    logits, _ = model(target_model_input(image, dataset_name))
    loss = CrossEntropyLoss()(logits, label)
    return torch.autograd.grad(
        loss,
        [param for _, param in parameters],
        retain_graph=create_graph,
        create_graph=create_graph,
        allow_unused=False,
    )


def refine_image(
    target_model,
    image,
    label,
    initialization,
    parameters,
    dataset_name,
    steps,
    lr,
    prior_weight,
    tv_weight,
):
    observed = tuple(
        grad.detach()
        for grad in gradients_for_image(
            target_model, image, label, parameters, dataset_name, create_graph=False
        )
    )
    candidate = initialization.detach().clone().requires_grad_(True)
    optimizer = torch.optim.Adam([candidate], lr=lr)
    trace = []
    for step in range(steps + 1):
        if step > 0:
            optimizer.zero_grad(set_to_none=True)
            target_model.zero_grad(set_to_none=True)
            current = gradients_for_image(
                target_model, candidate, label, parameters, dataset_name, create_graph=True
            )
            grad_loss = normalized_gradient_loss(current, observed)
            prior_loss = F.mse_loss(candidate, initialization)
            tv_loss = total_variation(candidate)
            objective = grad_loss + prior_weight * prior_loss + tv_weight * tv_loss
            objective.backward()
            torch.nn.utils.clip_grad_norm_([candidate], max_norm=5.0)
            optimizer.step()
            target_model.zero_grad(set_to_none=True)
            with torch.no_grad():
                candidate.clamp_(-1.0, 1.0)
        else:
            grad_loss = torch.zeros((), device=DEVICE)
            prior_loss = torch.zeros((), device=DEVICE)
            tv_loss = torch.zeros((), device=DEVICE)
        trace.append(
            {
                "step": step,
                "gradient_loss": float(grad_loss.detach().cpu().item()),
                "prior_loss": float(prior_loss.detach().cpu().item()),
                "tv_loss": float(tv_loss.detach().cpu().item()),
            }
        )
    return candidate.detach(), trace


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", choices=["celeba", "cifar10", "fashionmnist", "folder", "imagefolder"], required=True)
    parser.add_argument("--data_root", required=True)
    parser.add_argument("--target_weight", required=True)
    parser.add_argument("--decoder_path", required=True)
    parser.add_argument("--output_dir", required=True)
    parser.add_argument("--arch", choices=["vgg", "resnet18"], default="vgg")
    parser.add_argument("--img_size", type=int, default=64)
    parser.add_argument("--in_channels", type=int, default=3)
    parser.add_argument("--num_classes", type=int, default=0)
    parser.add_argument("--feature_dim", type=int, default=2048)
    parser.add_argument("--test_samples", type=int, default=100)
    parser.add_argument("--max_eval_scan", type=int, default=0)
    parser.add_argument("--num_workers", type=int, default=0)
    parser.add_argument("--label_source", choices=["pred", "dataset"], default="dataset")
    parser.add_argument("--gradient_scope", choices=["classifier", "full"], default="classifier")
    parser.add_argument("--steps", type=int, default=30)
    parser.add_argument("--lr", type=float, default=0.01)
    parser.add_argument("--prior_weight", type=float, default=0.01)
    parser.add_argument("--tv_weight", type=float, default=0.001)
    parser.add_argument("--save_pairs", type=int, default=20)
    parser.add_argument("--save_raw_pairs", action="store_true")
    parser.add_argument("--seed", type=int, default=2027)
    parser.add_argument("--manifest_path", default="")
    parser.add_argument("--manifest_partition", choices=["", "auxiliary", "validation", "test"], default="")
    args = parser.parse_args()
    seed_everything(args.seed)

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    transform = build_transform(args.dataset, args.img_size, args.in_channels)
    scan_limit = args.max_eval_scan if args.max_eval_scan > 0 else max(args.test_samples * 10, args.test_samples)
    dataset = build_dataset(
        args.dataset,
        args.data_root,
        "test",
        transform,
        scan_limit,
        False,
        manifest_path=args.manifest_path,
        manifest_partition=args.manifest_partition,
    )
    if args.label_source == "dataset" and hasattr(dataset, "has_complete_labels") and not dataset.has_complete_labels:
        raise RuntimeError("Dataset-label mode requires complete manifest labels")
    loader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=args.num_workers)
    target_model = load_target_model(
        args.target_weight, args.in_channels, args.num_classes, args.feature_dim, args.arch
    )
    target_model.eval()
    for parameter in target_model.parameters():
        parameter.requires_grad_(True)
    fc_parameters = [
        (name, parameter)
        for name, parameter in target_model.named_parameters()
        if name in {"fc_layer.weight", "fc_layer.bias"}
    ]
    parameters = select_parameters(target_model, args.gradient_scope)
    decoder = load_decoder(args.decoder_path, args.feature_dim, args.img_size, args.in_channels)
    decoder.eval()

    initial_psnr, refined_psnr = [], []
    initial_ssim, refined_ssim = [], []
    initial_id, refined_id = [], []
    per_sample, saturated = [], []
    for source_idx, (image, label) in enumerate(loader):
        if len(per_sample) >= args.test_samples:
            break
        image, label = image.to(DEVICE), label.to(DEVICE)
        with torch.no_grad():
            logits, _ = target_model(target_model_input(image, args.dataset))
            predicted = logits.argmax(dim=1)
        target_label = label if args.label_source == "dataset" else predicted
        try:
            observed_fc = gradients_for_image(
                target_model,
                image,
                target_label,
                fc_parameters,
                args.dataset,
                create_graph=False,
            )
            leaked_feature, recovered_class, denominator = recover_feat_from_fc_grad(
                observed_fc[0].detach(), observed_fc[1].detach(), target_label
            )
        except RuntimeError as exc:
            saturated.append({"source_idx": source_idx, "reason": str(exc)})
            continue
        with torch.no_grad():
            initialization = decoder(leaked_feature.to(DEVICE))
        refined, trace = refine_image(
            target_model,
            image,
            target_label,
            initialization,
            parameters,
            args.dataset,
            args.steps,
            args.lr,
            args.prior_weight,
            args.tv_weight,
        )
        init_psnr = float(compute_psnr(initialization, image).item())
        final_psnr = float(compute_psnr(refined, image).item())
        init_ssim = float(compute_ssim(initialization, image))
        final_ssim = float(compute_ssim(refined, image))
        init_id_loss = float(compute_id_loss(target_model, image, initialization, args.dataset).item())
        final_id_loss = float(compute_id_loss(target_model, image, refined, args.dataset).item())
        record = {
            "source_idx": source_idx,
            "target_label": int(target_label.item()),
            "pred_label": int(predicted.item()),
            "recovered_class": int(recovered_class),
            "recovered_denom": denominator,
            "initial_psnr": init_psnr,
            "refined_psnr": final_psnr,
            "initial_ssim": init_ssim,
            "refined_ssim": final_ssim,
            "initial_id_loss": init_id_loss,
            "refined_id_loss": final_id_loss,
            "trace": trace,
        }
        per_sample.append(record)
        initial_psnr.append(init_psnr)
        refined_psnr.append(final_psnr)
        initial_ssim.append(init_ssim)
        refined_ssim.append(final_ssim)
        initial_id.append(init_id_loss)
        refined_id.append(final_id_loss)
        if len(per_sample) <= args.save_pairs:
            save_pair(
                image,
                refined,
                output_dir,
                len(per_sample) - 1,
                {"psnr": final_psnr, "ssim": final_ssim, "id_loss": final_id_loss},
            )
        if args.save_raw_pairs:
            image_pair_save(image, refined, output_dir, f"{source_idx:04d}")
        print(
            f"Sample {len(per_sample):03d} src_idx={source_idx:04d} | "
            f"init {init_psnr:.2f} -> refined {final_psnr:.2f} dB"
        )

    if not per_sample:
        raise RuntimeError("No valid samples were recovered")
    summary = {
        "dataset": args.dataset,
        "method": "FAD initialization + differentiable gradient refinement",
        "gradient_scope": args.gradient_scope,
        "test_samples": len(per_sample),
        "requested_test_samples": args.test_samples,
        "scanned_samples": len(per_sample) + len(saturated),
        "saturated_samples": len(saturated),
        "refine_steps": args.steps,
        "initial_psnr": summarize_values(initial_psnr, seed=args.seed),
        "refined_psnr": summarize_values(refined_psnr, seed=args.seed),
        "initial_ssim": summarize_values(initial_ssim, seed=args.seed),
        "refined_ssim": summarize_values(refined_ssim, seed=args.seed),
        "initial_id_loss": summarize_values(initial_id, seed=args.seed),
        "refined_id_loss": summarize_values(refined_id, seed=args.seed),
        "mean_psnr_gain_db": float(np.mean(np.asarray(refined_psnr) - np.asarray(initial_psnr))),
        "mean_ssim_gain": float(np.mean(np.asarray(refined_ssim) - np.asarray(initial_ssim))),
        "args": vars(args),
        "per_sample": per_sample,
        "saturated": saturated,
    }
    (output_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print("=" * 78)
    print("FAD refinement summary")
    print("=" * 78)
    print(f"gradient_scope: {args.gradient_scope}")
    print(f"test_samples: {summary['test_samples']} / requested {args.test_samples}")
    print(f"initial PSNR: {summary['initial_psnr']['mean']:.2f} dB")
    print(f"refined PSNR: {summary['refined_psnr']['mean']:.2f} dB")
    print(f"mean PSNR gain: {summary['mean_psnr_gain_db']:+.2f} dB")
    print(f"initial SSIM: {summary['initial_ssim']['mean']:.4f}")
    print(f"refined SSIM: {summary['refined_ssim']['mean']:.4f}")
    print(f"summary_json: {output_dir / 'summary.json'}")


if __name__ == "__main__":
    main()
